"""Add new fields to User model

Revision ID: 40113aaa234e
Revises: 20260714_0001
Create Date: 2026-07-17 11:01:18.382932
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '40113aaa234e'
down_revision: str | None = '20260714_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('college', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('degree', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('graduation_year', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('target_company', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('current_cgpa', sa.String(length=10), nullable=True))
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'current_cgpa')
    op.drop_column('users', 'target_company')
    op.drop_column('users', 'graduation_year')
    op.drop_column('users', 'degree')
    op.drop_column('users', 'college')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###

