"""add_username_field

Revision ID: 4a7eba7c8e2c
Revises: 40113aaa234e
Create Date: 2026-07-17 14:14:01.942901
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4a7eba7c8e2c'
down_revision: str | None = '40113aaa234e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###

